#!/usr/bin/env bash
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true
export COPYFILE_DISABLE=true

VERSION='1.1'
NAME='ubnt_bcast_relay'
INSTALL="install_${NAME}.v${VERSION}"
PAYLOAD='payload'

if [[ -e "${0##*/}" ]]; then
	BASEDIR="$(pwd)"
	[[ -f ${INSTALL}.tgz ]] && rm ${INSTALL}.tgz

	cd ${PAYLOAD}
	echo ${VERSION} > version
	tar zcf ../${PAYLOAD}.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' ./*

	cd ..

	if [[ -e ${PAYLOAD}.tgz ]]; then
		cat decompress ${PAYLOAD}.tgz > ${INSTALL}
	else
		echo "${PAYLOAD}.tgz does not exist"
		exit 1
	fi

	chmod 0755 ${INSTALL}
	tar zcf ${INSTALL}.tgz ${INSTALL}
	echo "${INSTALL} created"

# Clean up so we're not pushing unneeded files to GitHub
	rm install_ubnt_bcast_relay.v1.1 payload.tgz

else
	echo "$(basename $0) must be run in the directory where it is located."
fi
exit 0
